[common]
# All properties defined in this section will be merged into each actor group's section.
# The primary purpose is to define default values of system settings (logging, dumping, and so on).

# Parameters and their defaults
# Logging
#system.logging.max_level = "Info" # one of: Trace, Debug, Info, Warn, Error, Off.
#system.logging.max_rate_per_level = 1000    # per second
#
# Dumping
#system.dumping.disabled = false
#system.dumping.max_rate = 100_000 # per second
#
# Telemetry
#system.telemetry.per_actor_group = true
#system.telemetry.per_actor_key = false

# Each parameter can be redefined on the actor group level.

[system.loggers]
#sink = "File"  # "Stdout" by default
#path = "example.log"
#format.with_location = false
#format.with_module = false
#
# Global max level filters all logs.
#max_level = "Info"
#
# It's possible to override `max_level` for a specific target:
#targets.hyper.max_level = "Trace"
#targets."hyper::server".max_level = "Warn"

[system.telemeters]
sink = "Prometheus"
address = "0.0.0.0:9042"
#global_labels = [["label", "value"]]
#quantiles = [0.75, 0.9, 0.95, 0.99]

[system.dumpers]
path = "example.{class}.dump"

[producers]
group_count = 3
item_count = 10

[aggregators]
system.telemetry.per_actor_key = true
#system.telemetry.per_actor_key = ["(.*)", "${1}-overrided"]

[reporters]
interval = "2s"
