[system.loggers]
#sink = "File"
#path = "example.log"

#format.with_location = true
#format.with_module = true

[system.dumpers]
path = "example.dump"

[producers]
group_count = 3
item_count = 10

[reporters]
interval = "2s"
